Repository gr4vy/gr4vy-embed, pull requests merged in 2021-11, with the labels that each got.

#33 fix: update theme type with missing label text
  packages/embed/src/types.ts
Labels: patch, release

#34 feat: add apple pay support
  packages/embed/package.json
  packages/embed/src/apple-pay/apple-pay.test.ts
  packages/embed/src/apple-pay/apple-pay.ts
  packages/embed/src/apple-pay/browser-support.test.ts
  packages/embed/src/apple-pay/browser-support.ts
  packages/embed/src/apple-pay/index.ts
  packages/embed/src/index.ts
  packages/embed/src/subjects.ts
  packages/embed/src/types.ts
  yarn.lock
Labels: minor, release

#35 Resolves issues cancelling Apple Pay
  packages/embed/src/apple-pay/apple-pay.test.ts
  packages/embed/src/apple-pay/apple-pay.ts
  packages/embed/src/index.ts
  packages/embed/src/subjects.ts
  packages/embed/src/utils/create-subject.ts
Labels: patch, release

#36 Fixes apple pay complete event pass-through
  packages/embed/src/index.ts
Labels: patch, release

#38 fix: update async tests
  packages/embed/src/apple-pay/apple-pay.test.ts
  packages/embed/src/form/form.test.ts
  packages/embed/src/frame/frame.test.ts
  packages/embed/src/overlay/overlay.test.ts
  packages/embed/src/popup/popup.test.ts
  packages/embed/src/skeleton/skeleton.test.ts
  packages/embed/src/subjects.test.ts
  packages/embed/src/utils/create-subject.ts
Labels: patch, release

#39 Change environment usage to point at different URLs
  packages/embed-cdn/README.md
  packages/embed-react/README.md
  packages/embed-react/src/index.stories.tsx
  packages/embed-react/src/index.test.tsx
  packages/embed/README.md
  packages/embed/src/create-config.test.ts
  packages/embed/src/create-config.ts
  packages/embed/src/types.ts
  packages/embed/src/validation.ts
Labels: major, release

#40 refactor: remove prefer response
  packages/embed-react/src/index.stories.tsx
  packages/embed/src/index.ts
  packages/embed/src/types.ts
  packages/embed/src/validation.ts
Labels: minor, internal
