Repository gr4vy/gr4vy-embed, pull requests merged in 2021-08, with the labels that each got.

#18 refactor: replace framebus with postMessage
  packages/embed/__mocks__/framebus.ts
  packages/embed/package.json
  packages/embed/src/emitter/emitter.test.ts
  packages/embed/src/emitter/emitter.ts
  packages/embed/src/emitter/index.ts
  packages/embed/src/index.ts
  packages/embed/src/types.ts
  packages/embed/src/utils/create-dispatch.test.ts
  packages/embed/src/utils/create-dispatch.ts
  packages/embed/src/utils/create-message-handler.test.ts
  packages/embed/src/utils/create-message-handler.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/logger.test.ts
  packages/embed/src/utils/logger.ts
  yarn.lock
Labels: patch, release

#19 Remove approve intent from documentation
  packages/embed-react/README.md
  packages/embed/README.md
Labels: documentation

#20 Add .trivyignore file
  .trivyignore
Labels: internal

#23 Upgrade dependencies
  packages/embed-react/src/__snapshots__/storyshots.test.ts.snap
  packages/embed-react/src/index.stories.tsx
  yarn.lock
Labels: internal

#24 Update dependencies
  package.json
  yarn.lock
Labels: patch, release, internal
