Repository gr4vy/gr4vy-embed, pull requests merged in 2022-01, with the labels that each got.

#54 fix: add postcss to trivyignore
  .trivyignore
Labels: internal

#53 Skeleton loader updated to fill the entire width of its container
  packages/embed/src/skeleton/skeleton.css
Labels: patch, release

#55 Added support for optionsLoaded event
  packages/embed-react/README.md
  packages/embed/README.md
  packages/embed/src/index.ts
  packages/embed/src/types.ts
Labels: minor

#51 feat(cart items): add support for cart items pass through [TA-458]
  packages/embed-react/README.md
  packages/embed/README.md
  packages/embed/src/index.ts
  packages/embed/src/types.ts
  packages/embed/src/validation.ts
Labels: minor

#56 Support for transactionFailed event when using onEvent
  packages/embed-react/README.md
  packages/embed/README.md
  packages/embed/src/index.ts
  packages/embed/src/types.ts
Labels: minor, release

#58 chore: CVE-2022-0155
  yarn.lock
Labels: patch, internal

#60 Updated contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#52 Add support for custom transaction statement descriptors
  packages/embed-react/README.md
  packages/embed/README.md
  packages/embed/src/index.ts
  packages/embed/src/types.ts
  packages/embed/src/validation.ts
Labels: minor, release

#63 Amount validation updated to match API maximum (99999999)
  .trivyignore
  packages/embed/src/validation.test.ts
  packages/embed/src/validation.ts
  yarn.lock
Labels: patch, release
