Repository gr4vy/gr4vy-embed, pull requests merged in 2022-04, with the labels that each got.

#74 task: add logging for when the gr4vyId is incorrect
  packages/embed/src/index.ts
  packages/embed/src/utils/logger.test.ts
  packages/embed/src/utils/logger.ts
Labels: minor, release, internal

#77 chore: upgrade async 2.6.4
  yarn.lock
Labels: patch, dependencies

#79 fix: pass-through approval cancelled event
  packages/embed/src/index.ts
Labels: patch, internal
