Repository gr4vy/gr4vy-embed, pull requests merged in 2022-11, with the labels that each got.

#107 chore: add gr4vy id as env variable
  .github/workflows/ci.yml
  package.json
  packages/embed/dev/index.ts
  yarn.lock
Labels: internal

#112 [PE-188] Remove deploy step for old storage bucket
  cloudbuild/deploy-env.yaml
Labels: internal

#111 feat: refocus redirect popup
  packages/embed/src/popup/popup.test.ts
  packages/embed/src/popup/popup.ts
Labels: patch, release

#113 feat: close popup before unload
  packages/embed/src/overlay/overlay.test.ts
  packages/embed/src/overlay/overlay.ts
Labels: patch, release

#115 feat: popup timeout
  packages/embed/README.md
  packages/embed/src/index.ts
  packages/embed/src/popup/popup.ts
  packages/embed/src/popup/redirect-popup.test.ts
  packages/embed/src/popup/redirect-popup.ts
  packages/embed/src/types.ts
  packages/embed/src/validation.ts
Labels: minor, release
