Repository gr4vy/gr4vy-embed, pull requests merged in 2022-06, with the labels that each got.

#84 task: Make it easier to understand loaded Embed/Embed UI
  .trivyignore
  packages/embed/jest.setup.js
  packages/embed/src/index.ts
  packages/embed/src/utils/index.ts
  packages/embed/src/utils/version.ts
  packages/embed/webpack.prod.js
Labels: release, internal

#86 Fix window.gr4vy.version declaration
  packages/embed/src/utils/version.ts
Labels: patch, release

#87 fix: embed version doesn't display anymore
  packages/embed/src/utils/version.ts
Labels: release, internal

#89 Add allow-popups and allow-top-navigation to sandboxed iframe
  packages/embed/src/frame/frame.test.ts
  packages/embed/src/frame/frame.ts
  packages/embed/src/overlay/overlay.ts
Labels: patch, release

#88 add approval ui dimensions
  packages/embed/src/popup/popup.test.ts
  packages/embed/src/popup/popup.ts
  packages/embed/src/subjects.ts
  packages/embed/webpack.dev.js
Labels: patch, release, internal

#92 test: add test for embed cdn
  packages/example-cdn/index.test.ts
  packages/example-cdn/package.json
  packages/example-cdn/playwright.config.ts
  yarn.lock
Labels: internal
