Repository gr4vy/gr4vy-embed, pull requests merged in 2022-05, with the labels that each got.

#76 chore: local development via http
  packages/embed-react/README.md
  packages/embed/README.md
  packages/embed/dev/index.ts
  packages/embed/src/create-config.ts
  packages/embed/src/types.ts
  packages/embed/src/utils/host-to-url.test.ts
  packages/embed/src/utils/host-to-url.ts
  packages/embed/src/validation.ts
Labels: minor, release

#81 task: add iframe content restrictions
  packages/embed/src/frame/frame.test.ts
  packages/embed/src/frame/frame.ts
  packages/embed/src/overlay/overlay.ts
Labels: minor, release

#82 Fix "save cache" Cloud Build step [PE-219]
  cloudbuild/cloudbuild-cdn.yaml
Labels: internal

#83 Fix pick function
  packages/embed/src/utils/pick.test.ts
  packages/embed/src/utils/pick.ts
Labels: patch, release
