Repository gr4vy/gr4vy-embed, pull requests merged in 2023-02, with the labels that each got.

#129 chore: update default api host
  .env.example
  packages/embed-react/dev/index.tsx
Labels: internal

#132 feat: add check for function onBeforeTransaction
  packages/embed/src/index.ts
  packages/embed/src/validation.test.ts
  packages/embed/src/validation.ts
Labels: patch, release

#133 feat: add delete payment option prop
  packages/embed-react/README.md
  packages/embed/README.md
  packages/embed/dev/index.ts
  packages/embed/src/create-config.test.ts
  packages/embed/src/create-config.ts
  packages/embed/src/index.ts
  packages/embed/src/types.ts
  packages/example-cdn/index.test.ts
Labels: minor, release
