Repository gr4vy/gr4vy-embed, pull requests merged in 2023-10, with the labels that each got.

#157 Cloud Build machineType
  cloudbuild/cloudbuild-cdn.yaml
  cloudbuild/deploy-env.yaml
Labels: internal

#158 fix: ignore/upgrade dev dependencies
  .trivyignore
  yarn.lock
Labels: internal

#159 feat: add prop to enable animations
  apps/example-cdn/index.test.ts
  packages/embed/README.md
  packages/embed/src/create-config.test.ts
  packages/embed/src/create-config.ts
  packages/embed/src/index.ts
  packages/embed/src/types.ts
Labels: release

#160 feat: add badgeBackgorund to theme
  packages/embed/src/types.ts
Labels: enhancement, release

#161 feat: add option to separate payment options
  apps/example-cdn/index.test.ts
  packages/embed/README.md
  packages/embed/src/create-config.test.ts
  packages/embed/src/create-config.ts
  packages/embed/src/index.ts
  packages/embed/src/types.ts
Labels: enhancement

#162 Update ci.yml
  .github/workflows/ci.yml
Labels: internal
