Repository gr4vy/gr4vy-embed, pull requests merged in 2024-10, with the labels that each got.

#228 deps: fix version of cookie
  package.json
  yarn.lock
Labels: patch, release, dependencies

#236 chore: remove unused `approve` intent from types and validation
  packages/embed-react/src/index.stories.tsx
  packages/embed/src/types.ts
  packages/embed/src/validation.test.ts
  packages/embed/src/validation.ts
Labels: patch, release

#229 trivy-db repository (again)
  .github/workflows/ci.yml
  cloudbuild/cloudbuild-cdn.yaml
Labels: internal
